### PR TITLE
utonics/labproject: use relative URLs in .gitmodules

### PR DESCRIPTION
**Pull request by achilleas-k**
Create relative URLs for the new submodules and write them back to the `.gitmodules` file.  This makes working with submodules much more flexible since it works for both git and http remotes, depending on how the parent repository is cloned. It also gets around any issues with linking in the GIN web interface.

@jcolomb please test it and let me know how it works for you.

### CODE REVIEW

**Comment by jcolomb** [comment]
Seems to work: https://gindata.biologie.hu-berlin.de/testtonic/testachilleastrick. 
I did not get to understand the branch issues.

**Review by jcolomb — CHANGES_REQUESTED** [review]
l298: os.Chdir("..") should also be changed to be sure it does not break another time

**Comment by jcolomb** [comment]
Adding `submoduleForEach("gin", "init")` in line 247 did the trick, but now it fails with

```
Failed to add repository "testing-gininit3.06_disseminations/02_manuscript" to team: 404 Not Found
```

**Comment by jcolomb** [comment]
So I added some changes to make it work without errors, could not make an extra branch, so commited directly (I did not think I could do that, but it worked...)

**Review by jcolomb — APPROVED** [review]
with the little changes, now works well, 

still do not really understand the branch issue.

**Comment by achilleas-k** [comment]
How does it work?  The commit you added doesn't compile.

What do you mean by "the branch issue"?

**Comment by jcolomb** [comment]
Sorry, I typed something while making a text search without noticing, I think this will do now.

**Comment by achilleas-k** [comment]
Please use the suggestion function to make recommendations for changes.  It's easier to review and discuss and keeps the git history cleaner.

**Comment by jcolomb** [comment]
Does not work when the changes to make are not in the changes you did. I will take the time to make a fork next time, sorry for the bother. (aiming at quick fixes are indeed never an efficient way to work... )

**Comment by achilleas-k** [comment]
Converted to draft to clean up and test additional changes.

**Comment by jcolomb** [comment]
apparently, the gin init on submodule is tricky, as it is not working with https://gindata.biologie.hu-berlin.de/G-Node/template_2, will look into it again.
note that the repo is still created, but tonic fail before adding the repo to the team.

log:
```
05. Cloning submodules
06. Failed to run command "gin init" in all submodules: exit status 128
```

and the terminal:

```
Entering '06_dissemination/02_manuscripts'
path='06_dissemination/02_manuscripts'; gin init: line 1: gin: not found
fatal: run_command returned non-zero status for 06_dissemination/02_manuscripts
.
```

**Comment by jcolomb** [comment]
close this one as the other PR is more advanced. will need to work there on ways to make subodules updates in tonic (sync script workaround works)

**Comment by jcolomb** [comment]
ok, checked again all changes were included in the other PR.

**Pull request closed without merging**
